-- MySQL Script generated by MySQL Workbench
-- Tue Aug 26 16:34:18 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Enviromap_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Enviromap_schema` ;
CREATE SCHEMA IF NOT EXISTS `Enviromap_schema` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Enviromap_schema` ;

-- -----------------------------------------------------
-- Table `Enviromap_schema`.`ProblemTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enviromap_schema`.`ProblemTypes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enviromap_schema`.`Problems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enviromap_schema`.`Problems` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(70) NULL,
  `Content` VARCHAR(500) NULL,
  `Severity` TINYINT UNSIGNED NULL,
  `Moderation` TINYINT(1) NULL,
  `Votes` SMALLINT UNSIGNED NULL,
  `Latitude` FLOAT(9,6) NULL,
  `Longtitude` FLOAT(9,6) NULL,
  `Status` TINYINT(1) NULL,
  `ProblemTypes_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC),
  INDEX `fk_Problems_ProblemTypes1_idx` (`ProblemTypes_Id` ASC),
  CONSTRAINT `fk_Problems_ProblemTypes1`
    FOREIGN KEY (`ProblemTypes_Id`)
    REFERENCES `Enviromap_schema`.`ProblemTypes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enviromap_schema`.`UserRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enviromap_schema`.`UserRoles` (
  `Id` INT NOT NULL,
  `Role` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enviromap_schema`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enviromap_schema`.`Users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Password` CHAR(64) NULL,
  `UserRoles_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Users_UserRoles1_idx` (`UserRoles_Id` ASC),
  CONSTRAINT `fk_Users_UserRoles1`
    FOREIGN KEY (`UserRoles_Id`)
    REFERENCES `Enviromap_schema`.`UserRoles` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enviromap_schema`.`Photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enviromap_schema`.`Photos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Link` VARCHAR(100) NULL,
  `Status` TINYINT(1) NULL,
  `Description` VARCHAR(200) NULL,
  `Problems_Id` INT NOT NULL,
  `Users_Id` INT NULL,
  PRIMARY KEY (`Id`, `Problems_Id`),
  INDEX `fk_Photos_Problems1_idx` (`Problems_Id` ASC),
  INDEX `fk_Photos_Users1_idx` (`Users_Id` ASC),
  CONSTRAINT `fk_Photos_Problems1`
    FOREIGN KEY (`Problems_Id`)
    REFERENCES `Enviromap_schema`.`Problems` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Photos_Users1`
    FOREIGN KEY (`Users_Id`)
    REFERENCES `Enviromap_schema`.`Users` (`Id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enviromap_schema`.`ActivityTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enviromap_schema`.`ActivityTypes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enviromap_schema`.`Activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enviromap_schema`.`Activities` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Content` VARCHAR(500) NULL,
  `Date` DATE NULL,
  `ActivityTypes_Id` INT NOT NULL,
  `Users_Id` INT NULL,
  `Problems_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Activities_ActivityTypes1_idx` (`ActivityTypes_Id` ASC),
  INDEX `fk_Activities_Users1_idx` (`Users_Id` ASC),
  INDEX `fk_Activities_Problems1_idx` (`Problems_Id` ASC),
  CONSTRAINT `fk_Activities_ActivityTypes1`
    FOREIGN KEY (`ActivityTypes_Id`)
    REFERENCES `Enviromap_schema`.`ActivityTypes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activities_Users1`
    FOREIGN KEY (`Users_Id`)
    REFERENCES `Enviromap_schema`.`Users` (`Id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activities_Problems1`
    FOREIGN KEY (`Problems_Id`)
    REFERENCES `Enviromap_schema`.`Problems` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
